import uniqid from 'uniqid';
import guts from './assets/guts-GA.webp';
import casca from './assets/casca-GA.png';
import griffith from './assets/Griffith_Card_GA.webp';
import pippin from './assets/Pippin_Manga.webp';
import judea from './assets/judea1.webp';
import zodd from './assets/zodd-fly.png';
import wylad from './assets/Wylad.webp';
import rickert from './assets/Rickert-Manga.webp';
import silat from './assets/Silat07.webp';
import skullknight from './assets/skull-knight.jpg';
import viod from './assets/void.webp';
import slan from './assets/slan.png';
import conrad from './assets/Conrad_Manga.webp';
import count from './assets/count.webp';
import snakeApostle from './assets/snake-apostle.jpg';
import femto from './assets/femto1.png';
import gutsArmor from './assets/berserk-guts-armor.png';
import beast from './assets/beast-of-darkness.webp';
import behelit from './assets/behelit.webp';
import puck from './assets/puck.png';
import schreike from './assets/Schierke_Render.webp';
import gaiseric from './assets/king-gaiseric.jpg';
import isidro from './assets/Isidro.webp';
import serpico from './assets/Serpico_wind.webp';
import rodrick from './assets/rodrick.jpg';
import farnese from './assets/Farnese_Manga.webp';


